### PR TITLE
Add FulfillmentChannel Array Param into the operation call

### PR DESCRIPTION
**Pull request by my-development**
Preparing the FulfillmentChannel param from array to query string

### CODE REVIEW

**Comment by hakanensari** [comment]
@my-development,

Thanks for the PR. Could you add `.idea` to a [global `.gitignore`][1], `git rm` the `.idea` artefacts, and `git rebase`?

[1]: https://gist.github.com/tonypujals/db7f57fff2fb6998a16c

**Comment by my-development** [comment]
Sure, no problem.

**Comment by hakanensari** [comment]
Thanks! I'm merging but will revert [f80daac][1] because those belong in a global gitignore on your computer rather than the project gitignore.

[1]: https://github.com/my-development/peddler/commit/f80daac6958bb03d085ff92501ea9a0ca58afeb1

**Comment by my-development** [comment]
:+1:

**Comment by my-development** [comment]
@hakanensari when are you planning to have next production release? thanks

**Comment by hakanensari** [comment]
@my-development very soon :smile:

**Comment by hakanensari** [comment]
@my-development released

**Comment by my-development** [comment]
@hakanensari  Awesome, I will get the updates! Thanks

**Pull request merged**
